name: container

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/chechout@v2
        with:
          ref: master
      - run: npm install
      - run: npm run build
